name: "Pull Request"
description: "Use this template to submit a pull request."
title: "[PR] "
labels: []
body:
  - type: markdown
    attributes:
      value: |
        ## Description

        ### What does this Pull Request do?
        Please select the appropriate option(s):
  - type: checkboxes
    id: change_type
    attributes:
      label: Type of Change
      options:
        - label: Bug Fix
        - label: New Feature
        - label: Code Improvement
        - label: Documentation Update
  - type: textarea
    id: changes_details
    attributes:
      label: Details of Changes
      description: List the key changes or updates in this PR. Include any relevant issue numbers, if applicable.
      placeholder: "Provide a short summary of the changes made."
  - type: textarea
    id: related_issues
    attributes:
      label: Related Issues
      description: Link any existing issue(s) that this PR addresses (e.g., Fixes #123). If no issues are related, leave this section empty.
      placeholder: "Fixes #..."
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Confirm the following before submitting the pull request:
      options:
        - label: Code compiles without errors.
        - label: All tests pass.
        - label: Changes have been tested on relevant devices.
        - label: Documentation updated (if necessary).
        - label: This PR is ready for review.
  - type: input
    id: esphome_version
    attributes:
      label: ESPHome Version
      placeholder: "e.g., 2024.7.0"
  - type: input
    id: samsung_ac_version
    attributes:
      label: samsung_ac Version
      placeholder: "e.g., 2024.7.0"
  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant Version
      placeholder: "e.g., 2024.7.0"
  - type: checkboxes
    id: ac_type
    attributes:
      label: Air Conditioner Type
      description: Select the type of air conditioner.
      options:
        - label: NASA
        - label: NON-NASA
        - label: Other
  - type: input
    id: ac_model
    attributes:
      label: Air Conditioner Model
      description: Enter the air conditioner's model number (e.g., AR09TXFCAWKNEU).
      placeholder: "e.g., AR09TXFCAWKNEU"
  - type: input
    id: outdoor_model
    attributes:
      label: Outdoor Unit Model
      description: Enter the outdoor unit's model number (e.g., AJ050TXJ2KH/EA).
      placeholder: "e.g., AJ050TXJ2KH/EA"
  - type: input
    id: esp_device_model
    attributes:
      label: ESP Device Model
      description: Enter the ESP device model used for this test (e.g., M5STACK ATOM Lite).
      placeholder: "e.g., M5STACK ATOM Lite + M5STACK RS-485"
  - type: input
    id: wiring_configuration
    attributes:
      label: Wiring Configuration
      description: Specify the wiring configuration for your ESP device (e.g., F1/F2).
      placeholder: "e.g., F1/F2"
  - type: textarea
    id: test_plan
    attributes:
      label: Test Plan
      description: Describe how the changes were tested. Include environment details, devices used, and test cases.
      placeholder: "Describe the testing process..."
