title: "[Question] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your interest in our project! Please fill out the form to ask a question.
  - type: input
    id: title
    attributes:
      label: Question Title
      description: "Provide a concise title for your question."
      placeholder: "Enter the main issue or question."
    validations:
      required: true
  - type: textarea
    id: question_description
    attributes:
      label: Question Description
      description: "Describe your question in detail, providing any necessary context."
      placeholder: "Describe the problem, question, or scenario you're dealing with..."
    validations:
      required: true
  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: "Select the type of issue."
      options:
        - Bug
        - Feature Request
        - General Question
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for submitting your question! We’ll get back to you soon.
